// Owuan Commerce - Dummy Data for Women's Fashion Store

import type { Product, Collection, Menu, Page } from './types';

// Helper to create product images
const createImage = (id: string, alt: string) => ({
  url: `https://images.unsplash.com/photo-${id}?w=800&h=1000&fit=crop`,
  altText: alt,
  width: 800,
  height: 1000,
});

// Product Images (Unsplash)
const productImages = {
  dress1: '1515372039744-b8f02a3ae446',
  dress2: '1572804013427-4d7ca7268217',
  dress3: '1595777457583-95e059d581b8',
  dress4: '1539008835657-9e8e9680c956',
  top1: '1564257631407-4deb1f99d992',
  top2: '1551488831-00ddcb6c6bd3',
  top3: '1562157873-818bc0726f68',
  top4: '1485968579580-b6d095142e6e',
  pants1: '1594633312681-425c7b97ccd1',
  pants2: '1541099649105-f69ad21f3246',
  pants3: '1584370848010-d7fe6bc767ec',
  skirt1: '1583496661160-fb5886a773a9',
  skirt2: '1582142839970-2b9e04b60f65',
  jacket1: '1591047139829-d91aecb6caea',
  jacket2: '1544022613-e87ca75a784a',
  accessory1: '1590548784585-643d2b9f2f43',
  accessory2: '1611085583191-a3b181a88401',
  bag1: '1548036328-c9fa89d128fa',
  bag2: '1584917865442-de89df76afd3',
  shoes1: '1543163521-1bf539c55dd2',
  shoes2: '1515347619252-60a4bf4fff4f',
};

export const products: Product[] = [
  // DRESSES
  {
    id: 'dress-1',
    handle: 'elegant-silk-evening-dress',
    title: 'Elegant Silk Evening Dress',
    description: 'A stunning silk evening dress perfect for special occasions. Features a flattering A-line silhouette with delicate draping.',
    descriptionHtml: '<p>A stunning silk evening dress perfect for special occasions. Features a flattering A-line silhouette with delicate draping.</p><ul><li>100% Pure Silk</li><li>Fully lined</li><li>Hidden back zipper</li></ul>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { id: 'color', name: 'Color', values: ['Black', 'Navy', 'Burgundy'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '299.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '299.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'dress-1-s-black', title: 'S / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Black' }], price: { amount: '299.00', currencyCode: 'USD' } },
      { id: 'dress-1-m-black', title: 'M / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Black' }], price: { amount: '299.00', currencyCode: 'USD' } },
      { id: 'dress-1-l-navy', title: 'L / Navy', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'L' }, { name: 'Color', value: 'Navy' }], price: { amount: '299.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.dress1, 'Elegant Silk Evening Dress'),
    images: [
      createImage(productImages.dress1, 'Elegant Silk Evening Dress - Front'),
      createImage(productImages.dress2, 'Elegant Silk Evening Dress - Back'),
    ],
    seo: { title: 'Elegant Silk Evening Dress | Owuan', description: 'Shop our stunning silk evening dress' },
    tags: ['dress', 'evening', 'silk', 'formal'],
    updatedAt: new Date().toISOString(),
    category: 'dresses',
    brand: 'Owuan Collection',
    rating: 4.8,
    reviewCount: 124,
    isNew: true,
    isBestseller: true,
  },
  {
    id: 'dress-2',
    handle: 'floral-midi-wrap-dress',
    title: 'Floral Midi Wrap Dress',
    description: 'A romantic floral print wrap dress with a flattering midi length. Perfect for daytime events and summer occasions.',
    descriptionHtml: '<p>A romantic floral print wrap dress with a flattering midi length.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Rose', 'Blue'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '159.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '159.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'dress-2-s-rose', title: 'S / Rose', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Rose' }], price: { amount: '159.00', currencyCode: 'USD' } },
      { id: 'dress-2-m-blue', title: 'M / Blue', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Blue' }], price: { amount: '159.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.dress3, 'Floral Midi Wrap Dress'),
    images: [createImage(productImages.dress3, 'Floral Midi Wrap Dress')],
    seo: { title: 'Floral Midi Wrap Dress | Owuan', description: 'Shop our floral midi wrap dress' },
    tags: ['dress', 'midi', 'floral', 'wrap'],
    updatedAt: new Date().toISOString(),
    category: 'dresses',
    brand: 'Owuan Collection',
    rating: 4.6,
    reviewCount: 89,
    isNew: false,
    isBestseller: true,
    discount: 20,
  },
  {
    id: 'dress-3',
    handle: 'little-black-dress',
    title: 'Classic Little Black Dress',
    description: 'The timeless LBD every woman needs. Sophisticated cut with modern details.',
    descriptionHtml: '<p>The timeless LBD every woman needs. Sophisticated cut with modern details.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '189.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '189.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'dress-3-s', title: 'S', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }], price: { amount: '189.00', currencyCode: 'USD' } },
      { id: 'dress-3-m', title: 'M', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }], price: { amount: '189.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.dress4, 'Classic Little Black Dress'),
    images: [createImage(productImages.dress4, 'Classic Little Black Dress')],
    seo: { title: 'Little Black Dress | Owuan', description: 'The timeless LBD' },
    tags: ['dress', 'black', 'classic', 'elegant'],
    updatedAt: new Date().toISOString(),
    category: 'dresses',
    brand: 'Owuan Collection',
    rating: 4.9,
    reviewCount: 256,
    isNew: false,
    isBestseller: true,
  },
  // TOPS
  {
    id: 'top-1',
    handle: 'silk-blouse-cream',
    title: 'Silk Blouse in Cream',
    description: 'Luxurious silk blouse with a relaxed fit. Features mother-of-pearl buttons and French seams.',
    descriptionHtml: '<p>Luxurious silk blouse with a relaxed fit.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Cream', 'White', 'Blush'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '149.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '149.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'top-1-s-cream', title: 'S / Cream', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Cream' }], price: { amount: '149.00', currencyCode: 'USD' } },
      { id: 'top-1-m-white', title: 'M / White', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'White' }], price: { amount: '149.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.top1, 'Silk Blouse in Cream'),
    images: [createImage(productImages.top1, 'Silk Blouse in Cream')],
    seo: { title: 'Silk Blouse | Owuan', description: 'Luxurious silk blouse' },
    tags: ['top', 'blouse', 'silk', 'elegant'],
    updatedAt: new Date().toISOString(),
    category: 'tops',
    brand: 'Owuan Collection',
    rating: 4.7,
    reviewCount: 67,
    isNew: true,
    isBestseller: false,
  },
  {
    id: 'top-2',
    handle: 'cashmere-sweater',
    title: 'Cashmere V-Neck Sweater',
    description: 'Ultra-soft cashmere sweater with a flattering V-neck. Perfect for layering or wearing alone.',
    descriptionHtml: '<p>Ultra-soft cashmere sweater with a flattering V-neck.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { id: 'color', name: 'Color', values: ['Camel', 'Grey', 'Navy', 'Black'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '229.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '229.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'top-2-s-camel', title: 'S / Camel', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Camel' }], price: { amount: '229.00', currencyCode: 'USD' } },
      { id: 'top-2-m-grey', title: 'M / Grey', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Grey' }], price: { amount: '229.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.top2, 'Cashmere V-Neck Sweater'),
    images: [createImage(productImages.top2, 'Cashmere V-Neck Sweater')],
    seo: { title: 'Cashmere Sweater | Owuan', description: 'Ultra-soft cashmere sweater' },
    tags: ['top', 'sweater', 'cashmere', 'knitwear'],
    updatedAt: new Date().toISOString(),
    category: 'tops',
    brand: 'Owuan Collection',
    rating: 4.8,
    reviewCount: 143,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'top-3',
    handle: 'linen-relaxed-shirt',
    title: 'Linen Relaxed Shirt',
    description: 'Breathable linen shirt with a relaxed fit. Perfect for warm weather styling.',
    descriptionHtml: '<p>Breathable linen shirt with a relaxed fit.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['White', 'Sky Blue', 'Sand'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '119.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '119.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'top-3-s-white', title: 'S / White', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'White' }], price: { amount: '119.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.top3, 'Linen Relaxed Shirt'),
    images: [createImage(productImages.top3, 'Linen Relaxed Shirt')],
    seo: { title: 'Linen Shirt | Owuan', description: 'Breathable linen shirt' },
    tags: ['top', 'shirt', 'linen', 'casual'],
    updatedAt: new Date().toISOString(),
    category: 'tops',
    brand: 'Owuan Collection',
    rating: 4.5,
    reviewCount: 52,
    isNew: true,
    isBestseller: false,
  },
  {
    id: 'top-4',
    handle: 'satin-camisole',
    title: 'Satin Camisole Top',
    description: 'Elegant satin camisole with adjustable straps. Layer under blazers or wear alone.',
    descriptionHtml: '<p>Elegant satin camisole with adjustable straps.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Champagne', 'Black', 'Ivory'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '79.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '79.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'top-4-s-champagne', title: 'S / Champagne', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Champagne' }], price: { amount: '79.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.top4, 'Satin Camisole Top'),
    images: [createImage(productImages.top4, 'Satin Camisole Top')],
    seo: { title: 'Satin Camisole | Owuan', description: 'Elegant satin camisole' },
    tags: ['top', 'camisole', 'satin', 'elegant'],
    updatedAt: new Date().toISOString(),
    category: 'tops',
    brand: 'Owuan Collection',
    rating: 4.6,
    reviewCount: 78,
    isNew: false,
    isBestseller: false,
    discount: 15,
  },
  // PANTS
  {
    id: 'pants-1',
    handle: 'high-waist-tailored-trousers',
    title: 'High-Waist Tailored Trousers',
    description: 'Sophisticated tailored trousers with a flattering high waist. Perfect for office or evening.',
    descriptionHtml: '<p>Sophisticated tailored trousers with a flattering high waist.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { id: 'color', name: 'Color', values: ['Black', 'Navy', 'Camel'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '169.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '169.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'pants-1-s-black', title: 'S / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Black' }], price: { amount: '169.00', currencyCode: 'USD' } },
      { id: 'pants-1-m-navy', title: 'M / Navy', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Navy' }], price: { amount: '169.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.pants1, 'High-Waist Tailored Trousers'),
    images: [createImage(productImages.pants1, 'High-Waist Tailored Trousers')],
    seo: { title: 'Tailored Trousers | Owuan', description: 'High-waist tailored trousers' },
    tags: ['pants', 'trousers', 'tailored', 'formal'],
    updatedAt: new Date().toISOString(),
    category: 'pants',
    brand: 'Owuan Collection',
    rating: 4.7,
    reviewCount: 112,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'pants-2',
    handle: 'wide-leg-palazzo-pants',
    title: 'Wide-Leg Palazzo Pants',
    description: 'Flowing wide-leg pants in a luxurious drape fabric. Effortlessly elegant.',
    descriptionHtml: '<p>Flowing wide-leg pants in a luxurious drape fabric.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Ivory', 'Black', 'Terracotta'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '139.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '139.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'pants-2-s-ivory', title: 'S / Ivory', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Ivory' }], price: { amount: '139.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.pants2, 'Wide-Leg Palazzo Pants'),
    images: [createImage(productImages.pants2, 'Wide-Leg Palazzo Pants')],
    seo: { title: 'Palazzo Pants | Owuan', description: 'Wide-leg palazzo pants' },
    tags: ['pants', 'palazzo', 'wide-leg', 'elegant'],
    updatedAt: new Date().toISOString(),
    category: 'pants',
    brand: 'Owuan Collection',
    rating: 4.5,
    reviewCount: 64,
    isNew: true,
    isBestseller: false,
  },
  {
    id: 'pants-3',
    handle: 'slim-fit-cigarette-pants',
    title: 'Slim-Fit Cigarette Pants',
    description: 'Classic cigarette pants with a modern slim fit. Ankle-length for a chic look.',
    descriptionHtml: '<p>Classic cigarette pants with a modern slim fit.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Black', 'White', 'Burgundy'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '129.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '129.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'pants-3-s-black', title: 'S / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Black' }], price: { amount: '129.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.pants3, 'Slim-Fit Cigarette Pants'),
    images: [createImage(productImages.pants3, 'Slim-Fit Cigarette Pants')],
    seo: { title: 'Cigarette Pants | Owuan', description: 'Slim-fit cigarette pants' },
    tags: ['pants', 'slim', 'cigarette', 'classic'],
    updatedAt: new Date().toISOString(),
    category: 'pants',
    brand: 'Owuan Collection',
    rating: 4.6,
    reviewCount: 89,
    isNew: false,
    isBestseller: false,
  },
  // SKIRTS
  {
    id: 'skirt-1',
    handle: 'pleated-midi-skirt',
    title: 'Pleated Midi Skirt',
    description: 'Elegant pleated midi skirt that moves beautifully. A versatile wardrobe staple.',
    descriptionHtml: '<p>Elegant pleated midi skirt that moves beautifully.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Champagne', 'Black', 'Forest Green'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '119.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '119.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'skirt-1-s-champagne', title: 'S / Champagne', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Champagne' }], price: { amount: '119.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.skirt1, 'Pleated Midi Skirt'),
    images: [createImage(productImages.skirt1, 'Pleated Midi Skirt')],
    seo: { title: 'Pleated Skirt | Owuan', description: 'Elegant pleated midi skirt' },
    tags: ['skirt', 'midi', 'pleated', 'elegant'],
    updatedAt: new Date().toISOString(),
    category: 'skirts',
    brand: 'Owuan Collection',
    rating: 4.7,
    reviewCount: 76,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'skirt-2',
    handle: 'leather-mini-skirt',
    title: 'Leather Mini Skirt',
    description: 'Edgy yet sophisticated leather mini skirt. Features a flattering A-line cut.',
    descriptionHtml: '<p>Edgy yet sophisticated leather mini skirt.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Black', 'Burgundy', 'Tan'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '199.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '199.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'skirt-2-s-black', title: 'S / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Black' }], price: { amount: '199.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.skirt2, 'Leather Mini Skirt'),
    images: [createImage(productImages.skirt2, 'Leather Mini Skirt')],
    seo: { title: 'Leather Skirt | Owuan', description: 'Sophisticated leather mini skirt' },
    tags: ['skirt', 'mini', 'leather', 'edgy'],
    updatedAt: new Date().toISOString(),
    category: 'skirts',
    brand: 'Owuan Collection',
    rating: 4.4,
    reviewCount: 45,
    isNew: true,
    isBestseller: false,
  },
  // JACKETS & OUTERWEAR
  {
    id: 'jacket-1',
    handle: 'classic-blazer',
    title: 'Classic Wool Blazer',
    description: 'Timeless wool blazer with a tailored fit. A wardrobe essential for any occasion.',
    descriptionHtml: '<p>Timeless wool blazer with a tailored fit.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['XS', 'S', 'M', 'L', 'XL'] },
      { id: 'color', name: 'Color', values: ['Black', 'Navy', 'Camel', 'Grey'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '289.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '289.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'jacket-1-s-black', title: 'S / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'S' }, { name: 'Color', value: 'Black' }], price: { amount: '289.00', currencyCode: 'USD' } },
      { id: 'jacket-1-m-camel', title: 'M / Camel', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Camel' }], price: { amount: '289.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.jacket1, 'Classic Wool Blazer'),
    images: [createImage(productImages.jacket1, 'Classic Wool Blazer')],
    seo: { title: 'Wool Blazer | Owuan', description: 'Classic wool blazer' },
    tags: ['jacket', 'blazer', 'wool', 'classic'],
    updatedAt: new Date().toISOString(),
    category: 'jackets',
    brand: 'Owuan Collection',
    rating: 4.9,
    reviewCount: 187,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'jacket-2',
    handle: 'trench-coat',
    title: 'Classic Trench Coat',
    description: 'The iconic trench coat reimagined in premium cotton gabardine.',
    descriptionHtml: '<p>The iconic trench coat reimagined in premium cotton gabardine.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Beige', 'Black', 'Navy'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '399.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '399.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'jacket-2-m-beige', title: 'M / Beige', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Beige' }], price: { amount: '399.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.jacket2, 'Classic Trench Coat'),
    images: [createImage(productImages.jacket2, 'Classic Trench Coat')],
    seo: { title: 'Trench Coat | Owuan', description: 'Classic trench coat' },
    tags: ['jacket', 'coat', 'trench', 'classic'],
    updatedAt: new Date().toISOString(),
    category: 'jackets',
    brand: 'Owuan Collection',
    rating: 4.8,
    reviewCount: 98,
    isNew: false,
    isBestseller: true,
  },
  // ACCESSORIES
  {
    id: 'accessory-1',
    handle: 'silk-scarf',
    title: 'Silk Print Scarf',
    description: 'Luxurious silk scarf with an exclusive print. Versatile styling possibilities.',
    descriptionHtml: '<p>Luxurious silk scarf with an exclusive print.</p>',
    availableForSale: true,
    options: [
      { id: 'color', name: 'Color', values: ['Floral', 'Geometric', 'Abstract'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '129.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '129.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'accessory-1-floral', title: 'Floral', availableForSale: true, selectedOptions: [{ name: 'Color', value: 'Floral' }], price: { amount: '129.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.accessory1, 'Silk Print Scarf'),
    images: [createImage(productImages.accessory1, 'Silk Print Scarf')],
    seo: { title: 'Silk Scarf | Owuan', description: 'Luxurious silk scarf' },
    tags: ['accessory', 'scarf', 'silk'],
    updatedAt: new Date().toISOString(),
    category: 'accessories',
    brand: 'Owuan Collection',
    rating: 4.6,
    reviewCount: 54,
    isNew: true,
    isBestseller: false,
  },
  {
    id: 'accessory-2',
    handle: 'leather-belt',
    title: 'Italian Leather Belt',
    description: 'Premium Italian leather belt with signature gold buckle.',
    descriptionHtml: '<p>Premium Italian leather belt with signature gold buckle.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['S', 'M', 'L'] },
      { id: 'color', name: 'Color', values: ['Black', 'Tan', 'Burgundy'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '89.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '89.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'accessory-2-m-black', title: 'M / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: 'M' }, { name: 'Color', value: 'Black' }], price: { amount: '89.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.accessory2, 'Italian Leather Belt'),
    images: [createImage(productImages.accessory2, 'Italian Leather Belt')],
    seo: { title: 'Leather Belt | Owuan', description: 'Premium Italian leather belt' },
    tags: ['accessory', 'belt', 'leather'],
    updatedAt: new Date().toISOString(),
    category: 'accessories',
    brand: 'Owuan Collection',
    rating: 4.7,
    reviewCount: 89,
    isNew: false,
    isBestseller: false,
  },
  // BAGS
  {
    id: 'bag-1',
    handle: 'leather-tote',
    title: 'Structured Leather Tote',
    description: 'Spacious structured tote in premium leather. Perfect for work or weekend.',
    descriptionHtml: '<p>Spacious structured tote in premium leather.</p>',
    availableForSale: true,
    options: [
      { id: 'color', name: 'Color', values: ['Black', 'Tan', 'Burgundy', 'Navy'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '349.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '349.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'bag-1-black', title: 'Black', availableForSale: true, selectedOptions: [{ name: 'Color', value: 'Black' }], price: { amount: '349.00', currencyCode: 'USD' } },
      { id: 'bag-1-tan', title: 'Tan', availableForSale: true, selectedOptions: [{ name: 'Color', value: 'Tan' }], price: { amount: '349.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.bag1, 'Structured Leather Tote'),
    images: [createImage(productImages.bag1, 'Structured Leather Tote')],
    seo: { title: 'Leather Tote | Owuan', description: 'Structured leather tote' },
    tags: ['bag', 'tote', 'leather'],
    updatedAt: new Date().toISOString(),
    category: 'bags',
    brand: 'Owuan Collection',
    rating: 4.8,
    reviewCount: 156,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'bag-2',
    handle: 'crossbody-bag',
    title: 'Mini Crossbody Bag',
    description: 'Chic mini crossbody with adjustable strap. Perfect for essentials.',
    descriptionHtml: '<p>Chic mini crossbody with adjustable strap.</p>',
    availableForSale: true,
    options: [
      { id: 'color', name: 'Color', values: ['Black', 'Blush', 'Sage'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '199.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '199.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'bag-2-black', title: 'Black', availableForSale: true, selectedOptions: [{ name: 'Color', value: 'Black' }], price: { amount: '199.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.bag2, 'Mini Crossbody Bag'),
    images: [createImage(productImages.bag2, 'Mini Crossbody Bag')],
    seo: { title: 'Crossbody Bag | Owuan', description: 'Mini crossbody bag' },
    tags: ['bag', 'crossbody', 'mini'],
    updatedAt: new Date().toISOString(),
    category: 'bags',
    brand: 'Owuan Collection',
    rating: 4.5,
    reviewCount: 67,
    isNew: true,
    isBestseller: false,
    discount: 10,
  },
  // SHOES
  {
    id: 'shoes-1',
    handle: 'pointed-toe-pumps',
    title: 'Pointed Toe Leather Pumps',
    description: 'Elegant pointed toe pumps in premium leather. 3-inch heel for all-day comfort.',
    descriptionHtml: '<p>Elegant pointed toe pumps in premium leather.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['36', '37', '38', '39', '40', '41'] },
      { id: 'color', name: 'Color', values: ['Black', 'Nude', 'Red'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '249.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '249.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'shoes-1-38-black', title: '38 / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: '38' }, { name: 'Color', value: 'Black' }], price: { amount: '249.00', currencyCode: 'USD' } },
      { id: 'shoes-1-39-nude', title: '39 / Nude', availableForSale: true, selectedOptions: [{ name: 'Size', value: '39' }, { name: 'Color', value: 'Nude' }], price: { amount: '249.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.shoes1, 'Pointed Toe Leather Pumps'),
    images: [createImage(productImages.shoes1, 'Pointed Toe Leather Pumps')],
    seo: { title: 'Leather Pumps | Owuan', description: 'Elegant pointed toe pumps' },
    tags: ['shoes', 'pumps', 'heels', 'leather'],
    updatedAt: new Date().toISOString(),
    category: 'shoes',
    brand: 'Owuan Collection',
    rating: 4.6,
    reviewCount: 134,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'shoes-2',
    handle: 'leather-ankle-boots',
    title: 'Leather Ankle Boots',
    description: 'Versatile ankle boots in supple leather. Block heel for stability and style.',
    descriptionHtml: '<p>Versatile ankle boots in supple leather.</p>',
    availableForSale: true,
    options: [
      { id: 'size', name: 'Size', values: ['36', '37', '38', '39', '40'] },
      { id: 'color', name: 'Color', values: ['Black', 'Brown', 'Tan'] },
    ],
    priceRange: {
      maxVariantPrice: { amount: '279.00', currencyCode: 'USD' },
      minVariantPrice: { amount: '279.00', currencyCode: 'USD' },
    },
    variants: [
      { id: 'shoes-2-38-black', title: '38 / Black', availableForSale: true, selectedOptions: [{ name: 'Size', value: '38' }, { name: 'Color', value: 'Black' }], price: { amount: '279.00', currencyCode: 'USD' } },
    ],
    featuredImage: createImage(productImages.shoes2, 'Leather Ankle Boots'),
    images: [createImage(productImages.shoes2, 'Leather Ankle Boots')],
    seo: { title: 'Ankle Boots | Owuan', description: 'Leather ankle boots' },
    tags: ['shoes', 'boots', 'ankle', 'leather'],
    updatedAt: new Date().toISOString(),
    category: 'shoes',
    brand: 'Owuan Collection',
    rating: 4.7,
    reviewCount: 98,
    isNew: true,
    isBestseller: false,
  },
];

export const collections: Collection[] = [
  {
    handle: 'new-arrivals',
    title: 'New Arrivals',
    description: 'Discover our latest additions to the collection',
    seo: { title: 'New Arrivals | Owuan', description: 'Shop new arrivals' },
    image: createImage(productImages.dress1, 'New Arrivals'),
    updatedAt: new Date().toISOString(),
    path: '/search/new-arrivals',
  },
  {
    handle: 'bestsellers',
    title: 'Bestsellers',
    description: 'Our most loved pieces',
    seo: { title: 'Bestsellers | Owuan', description: 'Shop bestsellers' },
    image: createImage(productImages.jacket1, 'Bestsellers'),
    updatedAt: new Date().toISOString(),
    path: '/search/bestsellers',
  },
  {
    handle: 'dresses',
    title: 'Dresses',
    description: 'From day to evening, find your perfect dress',
    seo: { title: 'Dresses | Owuan', description: 'Shop dresses' },
    image: createImage(productImages.dress2, 'Dresses'),
    updatedAt: new Date().toISOString(),
    path: '/search/dresses',
  },
  {
    handle: 'tops',
    title: 'Tops',
    description: 'Blouses, shirts, and more',
    seo: { title: 'Tops | Owuan', description: 'Shop tops' },
    image: createImage(productImages.top1, 'Tops'),
    updatedAt: new Date().toISOString(),
    path: '/search/tops',
  },
  {
    handle: 'pants',
    title: 'Pants',
    description: 'Tailored trousers and casual pants',
    seo: { title: 'Pants | Owuan', description: 'Shop pants' },
    image: createImage(productImages.pants1, 'Pants'),
    updatedAt: new Date().toISOString(),
    path: '/search/pants',
  },
  {
    handle: 'skirts',
    title: 'Skirts',
    description: 'Mini to maxi, find your style',
    seo: { title: 'Skirts | Owuan', description: 'Shop skirts' },
    image: createImage(productImages.skirt1, 'Skirts'),
    updatedAt: new Date().toISOString(),
    path: '/search/skirts',
  },
  {
    handle: 'jackets',
    title: 'Jackets & Coats',
    description: 'Outerwear for every season',
    seo: { title: 'Jackets | Owuan', description: 'Shop jackets' },
    image: createImage(productImages.jacket1, 'Jackets'),
    updatedAt: new Date().toISOString(),
    path: '/search/jackets',
  },
  {
    handle: 'accessories',
    title: 'Accessories',
    description: 'Complete your look',
    seo: { title: 'Accessories | Owuan', description: 'Shop accessories' },
    image: createImage(productImages.accessory1, 'Accessories'),
    updatedAt: new Date().toISOString(),
    path: '/search/accessories',
  },
  {
    handle: 'bags',
    title: 'Bags',
    description: 'Totes, crossbodies, and more',
    seo: { title: 'Bags | Owuan', description: 'Shop bags' },
    image: createImage(productImages.bag1, 'Bags'),
    updatedAt: new Date().toISOString(),
    path: '/search/bags',
  },
  {
    handle: 'shoes',
    title: 'Shoes',
    description: 'From heels to flats',
    seo: { title: 'Shoes | Owuan', description: 'Shop shoes' },
    image: createImage(productImages.shoes1, 'Shoes'),
    updatedAt: new Date().toISOString(),
    path: '/search/shoes',
  },
  {
    handle: 'sale',
    title: 'Sale',
    description: 'Limited time offers',
    seo: { title: 'Sale | Owuan', description: 'Shop sale items' },
    image: createImage(productImages.dress3, 'Sale'),
    updatedAt: new Date().toISOString(),
    path: '/search/sale',
  },
];

export const headerMenu: Menu[] = [
  { title: 'New Arrivals', path: '/search/new-arrivals' },
  { title: 'Dresses', path: '/search/dresses' },
  { title: 'Tops', path: '/search/tops' },
  { title: 'Pants', path: '/search/pants' },
  { title: 'Jackets', path: '/search/jackets' },
  { title: 'Accessories', path: '/search/accessories' },
  { title: 'Sale', path: '/search/sale' },
];

export const footerMenu: Menu[] = [
  { title: 'About Us', path: '/about' },
  { title: 'Contact', path: '/contact' },
  { title: 'Shipping & Returns', path: '/shipping' },
  { title: 'FAQ', path: '/faq' },
  { title: 'Privacy Policy', path: '/privacy' },
  { title: 'Terms of Service', path: '/terms' },
];

export const pages: Page[] = [
  {
    uid: 'dummy-about',
    slug: 'about',
    title: 'About Us',
    content: '<p>Owuan is a modern women\'s fashion brand dedicated to creating timeless, elegant pieces.</p>',
    metaTitle: 'About Us | Owuan',
    metaDescription: 'Learn about Owuan fashion brand',
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'dummy-contact',
    slug: 'contact',
    title: 'Contact',
    content: '<p>Get in touch with our team.</p>',
    metaTitle: 'Contact | Owuan',
    metaDescription: 'Contact us',
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
